### ISSUE TITLE
Preparation

### ISSUE THREAD

**Issue by tabakazu** [tabakazu/taba_apismpl#1]
Gin
https://github.com/gin-gonic/gin

auto reload Gin
https://github.com/codegangsta/gin

**Comment by tabakazu** [comment]
```dockerfile
# Dockerfile
FROM golang:1.11-alpine

RUN apk add --no-cache git && \
  git config --global http.sslVerify false && \
  go get -u github.com/codegangsta/gin && \
  go get -u github.com/golang/dep/cmd/dep

COPY ./api /go/src/api/
WORKDIR /go/src/api/
```

```yaml
# docker-compose.yml
version: '3'
services:
  api:
    build: .
    volumes:
      - ./api:/go/src/api/
    ports:
      - "3000:3000"
      - "8080:8080"
```

```sh
# set up a new project
$ docker-compose run --rm api dep init

# install the project's dependencies
$ docker-compose run --rm api dep encure
```
